[application]
name = "Study Topic Randomizer"
default_platform = "desktop"
asset_dir = "assets"

[bundle]
identifier = "com.peaknot.studyrandomizer"
publisher = "PeaKnot"
icon = ["assets/rand_icon.png"]
version = "0.1.0"

[web.app]

# HTML title tag content
title = "subject_randomizer"

# include `assets` in web platform
[web.resource]

# Additional CSS style files
style = []

# Additional JavaScript files
script = []

[web.resource.dev]

# Javascript code file
# serve: [dev-server] only
script = []
